apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo4-backend
  labels:
    app: yolo4
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo4
      component: backend
  template:
    metadata:
      labels:
        app: yolo4
        component: backend
    spec:
      containers:
        - name: backend
          image: edwinme/yolo4-backend:latest
          command: ["npm", "start"] 
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-database
            - name: MONGODB_URI
              value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb-service:27017/$(MONGODB_DATABASE)?authSource=admin"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: yolo4-backend-service
  labels:
    app: yolo4
    component: backend
spec:
  type: ClusterIP
  selector:
    app: yolo4
    component: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000