apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-scripts
  namespace: yolo4
data:
  init-mongo.js: |
    // Initialize the database and create a user with the correct privileges
    db = db.getSiblingDB('yolodb');

    db.createUser({
      user: 'username',
      pwd: 'password',
      roles: [
        { role: 'readWrite', db: 'yolodb' },
        { role: 'dbAdmin', db: 'yolodb' }
      ]
    });

    db.createCollection('products');
    print('Database and user initialized successfully');
