apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: yolo4
  labels:
    app: yolo4
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo4
      component: database
  template:
    metadata:
      labels:
        app: yolo4
        component: database
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0.14
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        - name: MONGO_INITDB_DATABASE
          value: yolodb
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: yolo4
  labels:
    app: yolo4
    component: database
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: yolo4
    component: database
