# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: yolo4-backend-service
  labels:
    app: yolo4
    component: backend
spec:
  selector:
    app: yolo4
    component: backend
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: yolo4-frontend-service
  labels:
    app: yolo4
    component: frontend
spec:
  selector:
    app: yolo4
    component: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
